basePath: /api
definitions:
  models.User:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: simple Url shortener application with auth
  title: Url shortener API
  version: "1.0"
paths:
  /auth/signin:
    post:
      consumes:
      - application/json
      description: returns user and set session-cookie
      parameters:
      - description: user params
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: login
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: register new user, returns user
      parameters:
      - description: user params
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: register new user
      tags:
      - auth
swagger: "2.0"
